server:
  port: 3001
spring:
  application:
    name: property-service
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/billybangdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: pda_billybang_admin